### ISSUE TITLE
Working with Non-standard Data Lab - error in Question 2 solution code (HTML notebook)

### ISSUE THREAD

**Issue by hahnjm** [brad-cannell/intro.r.public#18]
The question asks "What is patient 37’s date of admission?", but in the HTML Notebook, the solution is written incorrectly. **This needs to be updated.** 
```r
hospital <- hospital %>%
  mutate(
    dob     = as.Date(dob, \%B %d
```

**The solution found in the R notebook file is correct.**

**Comment by mbcann01** [comment]
Thank you for pointing this out, @hahnjm !
