### ISSUE TITLE
Update the links to the lab code files

### ISSUE THREAD

**Issue by mbcann01** [brad-cannell/intro.r.public#6]
# Overview

I moved the code (Rmd) files out of Dropbox when I moved course materials over to OneDrive. The code files are now in GitHub. Update the links in Canvas.

Unfortunately, there doesn't seem to be a good way to get a download link for an individual Rmd file stored on GitHub and add it to Canvas. Additionally, HTML files can't be viewed directly on GitHub the way they could on Dropbox. However, I still don't want to use four different cloud services (i.e., GitHub, Dropbox, OneDrive, and Google Drive) and I still want the version control that GitHub offers. 

I think the best workaround is to:

- Store the files on GitHub (for version control).
- Clone the GitHub repository to OneDrive.
- Use OneDrive links to the files in Canvas.

**Comment by hahnjm** [comment]
I just noticed that this week's Lab (coding tools and best coding practices) also has links to three different participants which seem to be still linked to Dropbox. I went ahead and used the links that were corrected from last week's lab, given that they are the same. IF not, please update accordingly.

**Comment by mbcann01** [comment]
Thank you, @hahnjm !
